export const DEFAULT_STRINGS: Record<string, string> = {
  reEnableAstroAssistant: "Re-enable Astro",
  astro: "Astro",
  openAstroAssistant: "Open Astro",
  astroAI: "Astro AI",
  beta: "Beta",
  astroMenu: "Astro menu",
  newChat: "New chat",
  aboutAstro: "About Astro",
  expandPanel: "Expand",
  turnOffAstro: "Turn off Astro",
  reattachToSide: "Re-attach to side",
  detachMoveResize: "Detach & resize",
  close: "Close",
  astroGreeting: "Hi! How can I help you today?",
  astroGreetingWithProduct: "Hi! I can help with {product}.",
  askAstro: "Ask Astro",
  helpfulResponse: "Helpful",
  unhelpfulResponse: "Unhelpful",
  thanksForFeedback: "Thanks for the feedback!",
  couldNotSaveTryAgain: "Couldn't save — try again?",
  whatWentWrong: "What went wrong?",
  inaccurate: "Inaccurate",
  harmfulUnsafe: "Harmful or unsafe",
  irrelevant: "Irrelevant",
  somethingElse: "Something else",
  dismiss: "Dismiss",
  submit: "Submit",
  addedToCart: "Added to cart!",
  claimFree: "Claim free",
  addToCartWithPrice: "Add to cart — {price}",
  thinking: "Thinking",
  contextLabel: "Context: {text}",
  askAQuestion: "Ask a question",
  askAFollowUp: "Ask a follow-up",
  askAnything: "Ask anything...",
  send: "Send",
  free: "Free",
  doesThisWorkWithMyEditor: "Does this work with my editor?",
  canIUseThisForClientWork: "Can I use this for client work?",
  whatsIncluded: "What's included?",
  howFastIsDelivery: "How fast is delivery?",
  whatFitsYourEdits: "What fits your edits?",
  isCheckoutSecure: "Is checkout secure?",
  licensingForClientWork: "Licensing for client work?",
};

export const DEFAULT_CHIPS: string[] = [
  "What fits your edits?",
  "Is checkout secure?",
  "How fast is delivery?",
  "Licensing for client work?",
];

export const DEFAULT_PRODUCT_CHIPS: string[] = [
  "Does this work with my editor?",
  "Can I use this for client work?",
  "What's included?",
  "How fast is delivery?",
];
